# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/135/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/135/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/virginie/Desktop/VITALE/Tesi/Codice/TAJIVEc++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/virginie/Desktop/VITALE/Tesi/Codice/TAJIVEc++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/135/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/135/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/virginie/Desktop/VITALE/Tesi/Codice/TAJIVEc++/CMakeFiles /home/virginie/Desktop/VITALE/Tesi/Codice/TAJIVEc++/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/virginie/Desktop/VITALE/Tesi/Codice/TAJIVEc++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TAJIVEdecomp

# Build rule for target.
TAJIVEdecomp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TAJIVEdecomp
.PHONY : TAJIVEdecomp

# fast build rule for target.
TAJIVEdecomp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/build
.PHONY : TAJIVEdecomp/fast

TAJIVEmain.o: TAJIVEmain.cpp.o

.PHONY : TAJIVEmain.o

# target to build an object file
TAJIVEmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/TAJIVEmain.cpp.o
.PHONY : TAJIVEmain.cpp.o

TAJIVEmain.i: TAJIVEmain.cpp.i

.PHONY : TAJIVEmain.i

# target to preprocess a source file
TAJIVEmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/TAJIVEmain.cpp.i
.PHONY : TAJIVEmain.cpp.i

TAJIVEmain.s: TAJIVEmain.cpp.s

.PHONY : TAJIVEmain.s

# target to generate assembly for a file
TAJIVEmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/TAJIVEmain.cpp.s
.PHONY : TAJIVEmain.cpp.s

src/TAJIVE.o: src/TAJIVE.cpp.o

.PHONY : src/TAJIVE.o

# target to build an object file
src/TAJIVE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/src/TAJIVE.cpp.o
.PHONY : src/TAJIVE.cpp.o

src/TAJIVE.i: src/TAJIVE.cpp.i

.PHONY : src/TAJIVE.i

# target to preprocess a source file
src/TAJIVE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/src/TAJIVE.cpp.i
.PHONY : src/TAJIVE.cpp.i

src/TAJIVE.s: src/TAJIVE.cpp.s

.PHONY : src/TAJIVE.s

# target to generate assembly for a file
src/TAJIVE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/src/TAJIVE.cpp.s
.PHONY : src/TAJIVE.cpp.s

src/TensorDyn.o: src/TensorDyn.cpp.o

.PHONY : src/TensorDyn.o

# target to build an object file
src/TensorDyn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/src/TensorDyn.cpp.o
.PHONY : src/TensorDyn.cpp.o

src/TensorDyn.i: src/TensorDyn.cpp.i

.PHONY : src/TensorDyn.i

# target to preprocess a source file
src/TensorDyn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/src/TensorDyn.cpp.i
.PHONY : src/TensorDyn.cpp.i

src/TensorDyn.s: src/TensorDyn.cpp.s

.PHONY : src/TensorDyn.s

# target to generate assembly for a file
src/TensorDyn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TAJIVEdecomp.dir/build.make CMakeFiles/TAJIVEdecomp.dir/src/TensorDyn.cpp.s
.PHONY : src/TensorDyn.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TAJIVEdecomp"
	@echo "... TAJIVEmain.o"
	@echo "... TAJIVEmain.i"
	@echo "... TAJIVEmain.s"
	@echo "... src/TAJIVE.o"
	@echo "... src/TAJIVE.i"
	@echo "... src/TAJIVE.s"
	@echo "... src/TensorDyn.o"
	@echo "... src/TensorDyn.i"
	@echo "... src/TensorDyn.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

